<?php require_once './templates/header.php'?>

<div class="viajes-container">
    <h3>Detalles del Viaje</h3>

    <table>
        <tbody>
            <tr>
                <th>Fecha</th>
                <td><?= $viaje->fecha ?></td>
            </tr>
            <tr>
                <th>Origen</th>
                <td><?= $viaje->origen ?></td>
            </tr>
            <tr>
                <th>Destino</th>
                <td><?= $viaje->destino ?></td>
            </tr>
            <tr>
                <th>Conductor</th>
                <td><?= $conductor->nombre ?></td>
            </tr>
            <tr>
                <th>Vehículo</th>
                <td><?= $conductor->vehiculo ?></td>
            </tr>
        </tbody>
    </table>
</div>
