<?php require_once './templates/header.php'?>
<div >
    <h3>Detalles del Conductor</h3>

    <table>
        
        <tbody>
            <tr>
                <td><strong>Nombre</strong></td>
                <td><?= $conductor->nombre ?></td>
            </tr>
            <tr>
                <td><strong>Vehículo</strong></td>
                <td><?= $conductor->vehiculo ?></td>
            </tr>
        </tbody>
    </table>
</div>